# Generated by Django 4.1 on 2022-08-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('COMEDY', 'COMEDY'), ('ROMANCE', 'ROMANCE')], max_length=8),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('MA', 'MALAYALAM'), ('TA', 'TAMIL'), ('HI', 'HINDI')], max_length=2),
        ),
    ]
