# Generated by Django 4.1 on 2022-08-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0011_movie_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_trailer', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_trailer',
        ),
    ]
