# Generated by Django 4.1 on 2022-08-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0012_movietrailer_remove_movie_movie_trailer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieTrailer',
        ),
    ]
