# Generated by Django 4.1 on 2022-08-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0013_delete_movietrailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
