# Generated by Django 4.1 on 2022-08-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0015_remove_movie_trailer_alter_movie_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
