# Generated by Django 4.1 on 2022-08-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0016_movie_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_trailer',
        ),
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.URLField(),
        ),
    ]
